"""empty message

Revision ID: f8f27690e73e
Revises: 0cfdeb7b3821
Create Date: 2019-04-16 16:38:10.661138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f27690e73e'
down_revision = '0cfdeb7b3821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('saved', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'list', ['id'])
    op.alter_column('list_item', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'list_item', ['id'])
    op.add_column('user', sa.Column('token', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'token')
    op.drop_constraint(None, 'list_item', type_='unique')
    op.alter_column('list_item', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'list', type_='unique')
    op.drop_column('list', 'saved')
    # ### end Alembic commands ###
